version: "3.9"

services:
  bot:
    build:
      - context: ../.
      - dockerfile: deployment/Dockerfile
    env_file:
    - ../.env
    restart: always

  db:
    image: postgres:15
    restart: always
    env_file:
    - ../.env
    ports:
    - "5432:5432"
